api_id: 2040
api_hash: "b18441a1ff607e10a989891a5462e627"

sessions_dir: "./sessions"
database: "./database.db"
proxies_file: "./proxies.txt"

safety:
  max_comments_per_day: 20
  delay_range: [5, 15]
